version: '3.4'
services:
  timesheet:
    image: pintra/timesheet
    hostname: timesheet
    networks:
      timesheetNetwork:
        ipv4_address: 172.20.199.3
    environment:
      DB_HOST: 172.20.199.2
    expose:
      - "8082"
    restart: on-failure:3
    ports:
      - "8082:8082"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    hostname: mysql
    networks:
      timesheetNetwork:
        ipv4_address: 172.20.199.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timesheet
networks:
  timesheetNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.199.1/24
