version: '3.8'
services:
  db:
    image: mysql
    container_name: timesheet-db
    restart: always
    environment:
      MYSQL_DATABASE: 'timesheet'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - timesheet-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  application:
    container_name: timesheet-application
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - timesheet-network
    depends_on:
      - "db"
networks:
  timesheet-network:
    name: timesheet-network
    driver: bridge
